### ISSUE TITLE
cython problems with Python 3.7.0

### ISSUE THREAD

**Issue by maximilianh** [bhargavchippada/forceatlas2#10]
I'm getting clang errors when doing "pip3 install fa2":

    fa2/fa2util.c:13592:13: error: no member named 'exc_traceback' in 'struct _ts'; did you mean 'curexc_traceback'?
        tstate->exc_traceback = local_tb;
                ^~~~~~~~~~~~~
                curexc_traceback
    /usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:238:15: note: 'curexc_traceback' declared here
        PyObject *curexc_traceback;
                  ^
    15 errors generated.
    error: command 'clang' failed with exit status 1

This may be because Python 3.7 has changed the Cython functions:
https://github.com/cython/cython/issues/1978

Could you re-cythonize the package ? Is there a way I can do that through pip?

**Comment by maximilianh** [comment]
I was able to install it without pip via setup.py, without any problem. This problem only affect the pip install.

**Comment by bhargavchippada** [comment]
The pip package comes with C files built with an earlier version of Cython and Python -> [files](https://pypi.org/project/fa2/#files) so that the user doesn't need to install Cython (Not a great idea in retrospect).
Here's the [setup.py](https://github.com/bhargavchippada/forceatlas2/blob/master/setup.py), the reason why setup.py works is because the C file is built according to the latest Cython and Python locally (C file is not included in source zip)
I believe an ideal pip package script would be to install Cython if not present and then build the C file according to the system's Cython and Python versions
I will try repackaging it to work this way, let me know if you can help me with the setup.py script :)

**Comment by maximilianh** [comment]
Thanks, yes thats' what I thought was happening. And sorry, I know nothing
about setup.py files yet.

On Mon, Jul 30, 2018 at 11:11 AM, Bhargav Chippada <notifications@github.com

**Comment by LisaSikkema** [comment]
Hi,
I run into the same error, also when I use setup.py for installation. Did you find another way around this by any chance?
Thank you.

**Comment by maximilianh** [comment]
As written above, I ended up installing it with setup.py.

On another machine, I'm on python3.6 and it's all fine now. I'm not using python3.7 anywhere now. The version mess with Python is making me pull my hair our. If we had just stayed on Python2.7 the world could have saved thousands of wasted engineering hours.

**Comment by CharlesWit** [comment]
Hi, I'm having the exact same problem here, trying to install with setup.py doesn't help and brings out the same error.
Is there anything new to this matter ?
Thank you.

**Comment by astair** [comment]
Moin,
I'm having the same issue when installing with pip. Installing through setup.py does not through an error but prints `Warning: uncompiled fa2util module.  Compile with cython for a 10-100x speed boost.` on import, even though fa2util seems to have been compiled.
Cheers!

**Comment by bhargavchippada** [comment]
@maximilianh @LisaSikkema @CharlesWit @astair 

Hi everyone,
This issue is now fixed in the latest release. Please try installing again.
You can install the package with or without installing Cython first.

    pip install fa2

Fix: If Cython is present then the .c file is rebuild locally during fa2 installation else the pre-generated .c file in the package is used.

### Changelog ([Latest Release v0.3.4](https://github.com/bhargavchippada/forceatlas2/tree/v0.3.4))
- Rebuild .c file if Cython is present during installation
- Use the pre-generated .c file if Cython is not installed
- Example python notebook added
- Rendering README.md with images on PyPI page

Note: You do not need to install Cython first but if the installation fails because of some changes in Cython functions like above then you can install Cython and try again so that the local rebuild of .c file kicks in instead of using the pre-generated C file.
Similarly, if you do not need to compile with Cython (i.e. build the .c file locally) then first uninstall Cython and then run 'pip install fa2'

Cheers!

**Comment by bhargavchippada** [comment]
Closing this issue. Please let me know if you need any further help :)
